FilmsWebApp/FilmsWebUI/FilmsWebUI/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmsWebUI.Models;
using FilmsBLL.Services;
using PagedList;
using Ninject;

namespace FilmsWebUI.Controllers
{
    public class ActorsController : Controller
    {
        [Inject]
        public ActorsService actorsService { get; set; }
        public string searchTemplate { get; set; }
       
        public ViewResult Index(string searchString, int? page)
        {

            if (searchString == null)
            {
                searchString = "";
            }

            ViewBag.SearchString = searchString;
            var actors = actorsService.getActorsFromDAL(searchString);


            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View("IndexTest",actors.ToPagedList(pageNumber, pageSize));
        }
        // GET: Actors/Details/5
        public ActionResult Details(Guid id)
        {            
            return View(actorsService.getActorFromDAL(id));
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        [HttpPost]
        public ActionResult Create(FilmsBLL.Models.Actor model)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View(model);
                }
                return View("Details", actorsService.addOrEditActorInDAL(model));
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Actors/Edit/5
        public ActionResult Edit(Guid id)
        {
            return View(actorsService.getActorFromDAL(id));
        }

        // POST: Actors/Edit/5
        [HttpPost]
        public ActionResult Edit(FilmsBLL.Models.Actor model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Index");
                }
                return View("Details", actorsService.addOrEditActorInDAL(model));
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(Guid id)
        {
            return View(actorsService.getActorFromDAL(id));
        }
        [HttpPost]
        public ActionResult Delete(FilmsBLL.Models.Actor model)
        {
            try
            {
                actorsService.deleteActorFromDAL(model);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Message = "Delete is inpossible.";
                return View();
            }
        }
        public ActionResult GetFilms(Guid id)
        {
            var a = actorsService.getActorWithFilmsFromDAL(id);
            return View(a);
        }
    }
}

FilmsWebApp/FilmsWebUI/FilmsWebUI/Controllers/FilmsController.cs
using FilmsBLL.Services;
using Ninject;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilmsWebUI.Controllers
{
    public class FilmsController : Controller
    {
        [Inject]
        public FilmService filmsService { get; set; }
        [Inject]
        public IFilmRecommendService s { get; set; }

        public ViewResult Index(string searchString, int? page)
        {

            if (searchString == null)
            {
                searchString = "";
            }

            ViewBag.SearchString = searchString;
            var films = filmsService.getFilmsIQueryable(searchString);

            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(films.ToPagedList(pageNumber, pageSize));
        }
        // GET: Actors/Details/5
        public ActionResult Details(Guid id)
        {
            return View(filmsService.getFilm(id));
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        [HttpPost]
        public ActionResult Create(FilmsBLL.Models.Film model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                return View("Details", filmsService.createOrUpdateFilm(model));
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Actors/Edit/5
        public ActionResult Edit(Guid id)
        {
            return View(filmsService.getFilm(id));
        }

        // POST: Actors/Edit/5
        [HttpPost]
        public ActionResult Edit(FilmsBLL.Models.Film model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                return View("Details", filmsService.createOrUpdateFilm(model));
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(Guid id)
        {
            return View(filmsService.getFilm(id));
        }
        [HttpPost]
        public ActionResult Delete(FilmsBLL.Models.Film model)
        {
            try
            {
                filmsService.deleteFilm(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Delete is inpossible.";
                return View(model);
            }
        }
        public ActionResult Recommend(Guid id)
        {
            var film = filmsService.getFilm(id);
            var result = s.recommend(new List<FilmsBLL.Models.Film> { film }, new List<FilmsBLL.Models.Film>(), 10);
            return View(result.Select(item => filmsService.getFilm(item.ID)));
        }
    }
}

FilmsWebApp/FilmsWebUI/FilmsWebUI/Views/Films/Create.cshtml
@model FilmsBLL.Models.Film

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FilmsWebApp/FilmsWebUI/FilmsWebUI/Views/Films/Details.cshtml
@model FilmsBLL.Models.Film

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FilmsWebApp/FilmsWebUI/FilmsWebUI/Views/Films/Edit.cshtml
@model FilmsBLL.Models.Film

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FilmsWebApp/FilmsWebUI/FilmsWebUI/Views/Films/FilmsList.cshtml
@model IEnumerable<FilmsBLL.Models.Film>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th>
            Actors
        </th>
        <th>
            Genres
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @if (item.actors != null)
            {
                <ul>
                    @foreach (var actor in item.actors)
                    {
                        <li>
                            @Html.ActionLink(actor.name,"Details", "Actors", new { id = actor.ID }, new { })
                        </li>
                    }
                </ul>
            }
        </td>
        
        @*
    <td>
        @Html.Partial("../Actors/ActorsList", item.actors)
    </td>*@
        <td>
            @if(item.genres!=null)
            {
                <ul>
                    @foreach (var genre in item.genres)
                    {
                        <li>
                            @Html.DisplayFor(genreItem => genre.name)
                        </li>
                    }
                </ul>
            }
        </td>
        <td>
            <ul>
                <li>@Html.ActionLink("Edit", "Edit", "Films", new { id = item.ID }, new { })</li>
                <li>@Html.ActionLink("Details", "Details","Films", new { id = item.ID }, new { }) </li>
                <li>@Html.ActionLink("Delete", "Delete", "Films", new { id = item.ID }, new { })</li>
                <li>@Html.ActionLink("Recommend", "Recommend", "Films", new { id = item.ID }, new { })</li>
            </ul>           
        </td>
    </tr>
}

</table>

FilmsWebApp/FilmsWebUI/FilmsWebUI/Views/Films/Index.cshtml
@model PagedList.IPagedList<FilmsBLL.Models.Film>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}



<h2>Films</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Films", FormMethod.Get))
{
    <p>
        Find by title: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

@Html.Partial("FilmsList",Model)
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, searchString = ViewBag.SearchString }))

FilmsWebApp/FilmsWebUI/FilmsWebUI/Views/Films/Recommend.cshtml
@model IEnumerable<FilmsBLL.Models.Film>

@{
    ViewBag.Title = "Recommend";
}

<h2>Recommend</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>